"""Train the distilled intake classifier head.

    cd backend && uv run python ../scripts/train_complaint_classifier.py [--write]

Pipeline: teacher-labeled chief complaints (data/complaint_examples.json,
labels clinically reviewed per string, NOT generated by the keyword lexicon)
plus the curated demo cohort -> Model2Vec static embeddings (a distilled
sentence-transformer, numpy-only at inference) -> multinomial logistic
regression trained here in plain numpy. Fully deterministic: zero-init on a
convex objective with a fixed iteration count, no random seed anywhere.

The trained head (weights, classes, thresholds) is committed to
data/complaint_model/head.npz; the ~30MB embedding model is pulled once from
the Hugging Face hub (public, MIT) and baked into the server image at build
time - weights do not live in git.
"""

import argparse
import json
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "backend"))

from app.config import REPO_ROOT  # noqa: E402
from app.engine.complaint_ml import EMBED_MODEL, HEAD_PATH, HIGH_RISK_THRESHOLD, BENIGN_THRESHOLD  # noqa: E402

EXAMPLES_PATH = REPO_ROOT / "data" / "complaint_examples.json"
CURATED_PATH = REPO_ROOT / "data" / "curated_patients.json"

L2 = 1e-3
LR = 2.0
STEPS = 4000


def load_dataset() -> tuple[list[str], list[str]]:
    rows = json.loads(EXAMPLES_PATH.read_text())["examples"]
    texts = [r["text"] for r in rows]
    labels = [r["category"] for r in rows]
    for p in json.loads(CURATED_PATH.read_text()):
        texts.append(p["chief_complaint"])
        labels.append(p["complaint_category"])
    return texts, labels


def embed(texts: list[str]) -> np.ndarray:
    from model2vec import StaticModel

    model = StaticModel.from_pretrained(EMBED_MODEL)
    x = model.encode(texts).astype(np.float64)
    norms = np.linalg.norm(x, axis=1, keepdims=True)
    return x / np.maximum(norms, 1e-9)


def train_softmax(x: np.ndarray, y: np.ndarray, k: int,
                  steps: int = STEPS) -> tuple[np.ndarray, np.ndarray]:
    n, d = x.shape
    w = np.zeros((d, k))
    b = np.zeros(k)
    onehot = np.eye(k)[y]
    # class-balanced loss: a 4-example high-risk class must not be swamped
    # by the large "other" class - the safety asymmetry starts in training
    counts = onehot.sum(axis=0)
    sample_w = (n / (k * counts[y]))[:, None]
    for _ in range(steps):
        logits = x @ w + b
        logits -= logits.max(axis=1, keepdims=True)
        p = np.exp(logits)
        p /= p.sum(axis=1, keepdims=True)
        grad = (sample_w * (p - onehot)) / n
        w -= LR * (x.T @ grad + L2 * w)
        b -= LR * grad.sum(axis=0)
    return w, b


def predict(x, w, b) -> np.ndarray:
    logits = x @ w + b
    logits -= logits.max(axis=1, keepdims=True)
    p = np.exp(logits)
    return p / p.sum(axis=1, keepdims=True)


def cross_validate(x, y, classes, folds: int = 5) -> None:
    n = len(y)
    idx = np.arange(n)  # deterministic contiguous folds; data order is fixed
    correct, per_class = 0, {c: [0, 0] for c in classes}
    for f in range(folds):
        test = idx[f::folds]
        train = np.setdiff1d(idx, test)
        w, b = train_softmax(x[train], y[train], len(classes))
        pred = predict(x[test], w, b).argmax(axis=1)
        for t, p in zip(y[test], pred):
            per_class[classes[t]][1] += 1
            if t == p:
                correct += 1
                per_class[classes[t]][0] += 1
    print(f"5-fold accuracy: {correct / n * 100:.1f}% (n={n})")
    for c, (hit, tot) in sorted(per_class.items()):
        if tot:
            print(f"  {c:24s} recall {hit / tot * 100:5.1f}%  (n={tot})")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true", help="save the trained head")
    args = ap.parse_args()

    texts, labels = load_dataset()
    classes = sorted(set(labels))
    y = np.array([classes.index(c) for c in labels])
    print(f"dataset: {len(texts)} examples, {len(classes)} classes")
    x = embed(texts)

    cross_validate(x, y, classes)

    w, b = train_softmax(x, y, len(classes))
    train_acc = (predict(x, w, b).argmax(axis=1) == y).mean() * 100
    print(f"full-fit train accuracy: {train_acc:.1f}%")

    if args.write:
        HEAD_PATH.parent.mkdir(parents=True, exist_ok=True)
        np.savez(HEAD_PATH, w=w, b=b, classes=np.array(classes),
                 embed_model=EMBED_MODEL,
                 high_risk_threshold=HIGH_RISK_THRESHOLD,
                 benign_threshold=BENIGN_THRESHOLD)
        print(f"saved -> {HEAD_PATH}")


if __name__ == "__main__":
    main()
